[vim bindings] Disable jsdoc for findWord by doing /* instead of /**
This is to prevent the closure compiler from failing with

bazel-out/darwin_x86_64-fastbuild/bin/polygerrit-ui/app/gr-app.js:51233: ERROR - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
     * @return {Object{from:number, to:number, line: number}} The boundaries of
                      ^
  ProTip: "JSC_TYPE_PARSE_ERROR" or "checkTypes" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib
  Alternatively /** @suppress {checkTypes} */ can be added to the source file.

1 error(s), 1 warning(s)